version: '3'

volumes:
  c-sharp-projects-source:
    external: true
                                                            
services:
  c-sharp:
    build: .
    volumes:
      - c-sharp-projects-source:/workspace
      - ~/.gitconfig:/root/.gitconfig
    command: sleep infinity
    ports:
      - "5000:5000"
      - "5001:5001"
      # remap Mysql port
      - "9306:3306"

# vim: ai ts=2 sw=2 sts=2 ft=yaml
